Tripadvisor/Models/Hotel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Tripadvisor.Models
{
    public class Hotel
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public int Rating { get; set; }
        public Location location { get; set; }
        public List<Review> Reviews;
    }
}

Tripadvisor/Controllers/HotelsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using TripadvisorService;

namespace Tripadvisor.Controllers
{
    public class HotelsController : Controller
    {
        //
        // GET: /Hotels/

        public ActionResult Index()
        {
            return View();
        }

        //
        // GET: /Hotels/Details/5

        public ActionResult Details(string name)
        {
            Mapper.CreateMap<TripadvisorService.Review, Models.Review>();
            Mapper.CreateMap<TripadvisorService.Location, Models.Location>();
            Mapper.CreateMap<TripadvisorService.Hotel, Models.Hotel>();

            var client = new TripadvisorServiceClient();
            var hotel = client.GetHotelByName(name);
            var hotelObj = Mapper.Map<TripadvisorService.Hotel, Models.Hotel>(hotel);
            
            return View(hotelObj);
        }

        //
        // GET: /Hotels/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Hotels/Create

        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Hotels/Edit/5

        public ActionResult Edit(int id)
        {
            return View();
        }

        //
        // POST: /Hotels/Edit/5

        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Hotels/Delete/5

        public ActionResult Delete(int id)
        {
            return View();
        }

        //
        // POST: /Hotels/Delete/5

        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Tripadvisor/Views/Hotels/Details.cshtml
@model Tripadvisor.Models.Hotel

@{
    ViewBag.Title = @Model.Name;
}

<h2>@Model.Name</h2>

<fieldset>
    
    <div class="display-rating">
         @Html.DisplayNameFor(model => model.Rating)
        @Html.DisplayFor(model => model.Rating)
    </div>

    <div class="display-address">
        @Html.DisplayFor(model => model.location.Address)
        @Html.DisplayFor(model => model.location.City)
        @Html.DisplayFor(model => model.location.Country)
    </div>    
</fieldset>

<ul>
@foreach (var review in @Model.Reviews)
{
     <li>
        <p> @review.Title</p>
        <p>@review.Description</p>
        <p>Rating : @review.Rating</p>
        <p>Added By : @review.AddedByUserName</p>
        <p>Added At Time : @review.UTCAddedOn</p>
     </li>   
}
</ul>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Tripadvisor/Views/Hotels/Index.cshtml
@model Tripadvisor.Models.Hotel

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

@using (Html.BeginForm("Details","Hotels"))
{
    @Html.Label("Enter the Hotel Name")
    @Html.TextBox("name")
    <input type="submit" value="search" />
}
        